# Setup
title:               Minds&Company
tagline:             'AI Tech Blog'
description:         '<a href="http://mnc.ai/" target="_blank">마인즈앤컴퍼니</a>의 AI tech blog입니다. Made by <a href="https://www.linkedin.com/in/jiryang/" target="_blank">뱀눈</a>.'
url:                 https://jiryang.github.io
repository:          jiryang/jiryang.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ji Ryang Chung
  url:               https://www.linkedin.com/in/jiryang/
  email:             jr.chung@mindslab.ai

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
